"""Re-record the README demo GIF (docs/img/demo.gif) from examples/demo.tape.

The GIF is recorded with charmbracelet/vhs, which drives a headless terminal
(ttyd) and stitches the frames together with ffmpeg. Run this whenever the tape
changes:

    uv run python scripts/render_demo.py

Unlike scripts/render_docs_qr.py there is no ``--check`` drift guard: vhs
output is not byte-reproducible (frame timing, anti-aliasing and the GIF palette
all vary run to run) and rendering needs vhs + ttyd + ffmpeg, none of which CI
has. The GIF is a committed asset, regenerated by hand.

vhs is a Go binary; if your system has no package for it, install it with
``go install github.com/charmbracelet/vhs@latest`` (it lands in ~/go/bin).
"""

import re
import shutil
import subprocess
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

console = Console()
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TAPE = REPO_ROOT / "examples" / "demo.tape"
# `go install` drops vhs here when it is not packaged system-wide.
GO_BIN_VHS = Path.home() / "go" / "bin" / "vhs"
# vhs shells out to these at render time; `cuere` is what the tape itself runs.
REQUIRED_TOOLS = ("ttyd", "ffmpeg", "cuere")
# vhs `Output` may be indented and the path may be quoted: `Output "a/b.gif"`.
_OUTPUT = re.compile(r'^\s*Output\s+"?(?P<path>[^"]+?)"?\s*$')


class DemoRenderError(Exception):
    """A prerequisite for rendering the demo GIF is missing."""


def _rel(path: Path) -> str:
    """Display PATH relative to the repo root when it lives under it."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _resolve_vhs() -> str:
    """Return the vhs executable, falling back to ~/go/bin/vhs."""
    found = shutil.which("vhs")
    if found is not None:
        return found
    if GO_BIN_VHS.is_file():
        return str(GO_BIN_VHS)
    msg = (
        "vhs not found on PATH or in ~/go/bin -- install it with "
        "`go install github.com/charmbracelet/vhs@latest`"
    )
    raise DemoRenderError(msg)


def _require_tools() -> None:
    """Ensure vhs's render-time tools and the cuere CLI are all on PATH."""
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        hint = " (run `uv sync` to install cuere)" if "cuere" in missing else ""
        msg = f"missing on PATH: {', '.join(missing)}{hint}"
        raise DemoRenderError(msg)


def _tape_output(tape: Path) -> Path | None:
    """Return the file the tape writes to (its first ``Output`` directive)."""
    for line in tape.read_text(encoding="utf-8").splitlines():
        match = _OUTPUT.match(line)
        if match is not None:
            return (REPO_ROOT / match["path"]).resolve()
    return None


def main(
    tape: Annotated[
        Path,
        typer.Argument(help="The vhs tape to record."),
    ] = DEFAULT_TAPE,
) -> None:
    """Re-record the demo GIF from a vhs tape (default: examples/demo.tape)."""
    tape = tape.resolve()
    try:
        vhs = _resolve_vhs()
        _require_tools()
    except DemoRenderError as exc:
        console.print(f"[red]error[/] {exc}")
        raise typer.Exit(1) from exc

    console.print(f"recording [cyan]{_rel(tape)}[/] with vhs ...")
    # vhs runs from the repo root so the tape's relative `Output` path resolves there.
    result = subprocess.run([vhs, str(tape)], cwd=REPO_ROOT, check=False)
    if result.returncode != 0:
        console.print("[red]vhs failed[/] -- see its output above")
        raise typer.Exit(result.returncode)

    output = _tape_output(tape)
    if output is not None and output.is_file():
        size_kib = output.stat().st_size / 1024
        console.print(f"[green]wrote[/] {_rel(output)} ({size_kib:.0f} KiB)")
    else:
        console.print("[green]done[/]")


if __name__ == "__main__":
    typer.run(main)
